### PR TITLE
Add method to fetch list of available reports

### PR DESCRIPTION
**Pull request by johncarney**
Adds a method to fetch the list of available reports.

### CODE REVIEW

**Comment by owenbyrne** [comment]
I think we should extend `insight_client_spec` to specify the report names we want back.  That way, when we run `rake pact:verify` against insight, we'll know if we make any changes that might affect the users (i.e. removing a report will throw an error).

**Comment by supermario** [comment]
@owenbyrne not quite sure this is what we want... isn't the whole point of having a report listing endpoint that you _don't_ have to hardcode what reports exist where?

The consumer contract should definitely be updated to expect to see a listing of reports, but probably not what that exact listing is (otherwise we have the same problem when adding new reports).

**Comment by owenbyrne** [comment]
@supermario While having the report names defined in Insight itself cuts down on duplication and silly naming errors, I think the PACT test is very much worth it in this case.  

MOS expects to have access to a sales summary report/hotel commission report etc as core reporting functionality.  There should be a barrier to a dev removing/renaming them without being alerted.

**Comment by supermario** [comment]
Ok yes – agree with you in that case, but only if MOS _only_ specifies the reports that it must have, not just a blanket "these happened to be the reports that were supported at the time" so that it breaks everytime we add/remove reports not critical to MOS.

**Comment by supermario** [comment]
owjfoiwejfweojfowj

**Comment by johncarney** [comment]
Totally agree with @supermario here. A test that asserts that Insight supplies a minimum set of specific reports required by MOS is a good idea, but I'd rather not have any contractual test at all if the only option is "you must supply exactly this list of reports, no more, no less". The point of this exercise is to loosen the coupling between MOS and Insight, not tightly couple it in a different place.

**Pull request merged**
